# Generated by Django 6.0.1 on 2026-03-06 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_theater_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='trailer_id',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='reserved_at',
        ),
        migrations.RemoveField(
            model_name='seat',
            name='status',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='location',
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[('telugu', 'TELUGU'), ('hindi', 'HINDI'), ('english', 'ENGLISH')], default='telugu', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
        migrations.AddField(
            model_name='seat',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seat',
            name='theater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.theater'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genre',
            name='language',
            field=models.CharField(choices=[('telugu', 'TELUGU'), ('hindi', 'HINDI'), ('english', 'ENGLISH')], default='telugu', max_length=20),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AlterField(
            model_name='theater',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.genre'),
        ),
    ]
