# Generated by Django 6.0.1 on 2026-03-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_created_at_remove_movie_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
